SELECT  DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE
        , PRODUCT_ID, USER_ID, SALES_AMOUNT
  FROM  (
      SELECT  SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
        FROM  ONLINE_SALE
       UNION
      SELECT  SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
        FROM  OFFLINE_SALE
  )  AS COMBINED
 WHERE  SALES_DATE LIKE '2022-03%'
 ORDER
    BY  SALES_DATE, PRODUCT_ID, USER_ID

# 임시로 만든 테이블에는 꼭 이름을 붙여야 한다.
# NULL AS USER_ID 대신에 COALESCE(NULL, NULL) AS USER_ID 도 가능