# 1. COALESCE
SELECT  WAREHOUSE_ID
        ,WAREHOUSE_NAME	
        ,ADDRESS	
        ,COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
  FROM  FOOD_WAREHOUSE
 WHERE  ADDRESS	LIKE '경기%'
 ORDER
    BY  WAREHOUSE_ID ASC

# 2. CASE, IS NULL
SELECT  WAREHOUSE_ID
        ,WAREHOUSE_NAME	
        ,ADDRESS	
        ,CASE WHEN FREEZER_YN IS NULL THEN 'N'
              ELSE FREEZER_YN
         END  AS FREEZER_YN
  FROM  FOOD_WAREHOUSE
 WHERE  ADDRESS	LIKE '경기%'
 ORDER
    BY  WAREHOUSE_ID ASC

# 3. IFNULL
SELECT  WAREHOUSE_ID
        ,WAREHOUSE_NAME	
        ,ADDRESS	
        ,IFNULL(FREEZER_YN,'N')
  FROM  FOOD_WAREHOUSE
 WHERE  ADDRESS	LIKE '경기%'
 ORDER
    BY  WAREHOUSE_ID ASC